default:
    image: python:3.8
    before_script:
       - pip install -U pip
       - pip install poetry 
       - poetry install
stages:
    - formatting

formatting:
    stage: formatting
    script:
        - poetry run isort --check-only vibdata/ tests/
        - poetry run black --check vibdata/ tests/
    only:
        - merge_requests
